name: sync to S3

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Actualiza a la versión 4

      - name: Set up JDK 17
        uses: actions/setup-java@v3  # Configura Java 17
        with:
          distribution: 'temurin'  # Especifica la distribución de JDK
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Clean previous artifacts
        run: rm -rf target/*.jar

      - name: Build with Maven
        run: mvn clean compile package -DskipTests  # Ejecuta comandos Maven para compilar y empaquetar

      - name: List target directory
        run: ls -l target/  # Verifica que el archivo JAR está presente
      
      - name: Print working directory
        run: pwd  # Imprime el directorio de trabajo actual
    #Ohno
      - name: Delete previous artifacts in S3
        run: aws s3 rm s3://${{ secrets.AWS_S3_BUCKET }}/ --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'
      #Oh no

      - name: Upload JAR to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'
          SOURCE_DIR: 'target'  # JAR file source on github Workflows directory
          DEST_DIR: ''  # destination folder on S3 Bucket
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_EC2_SSH_KEY }}
      - name: Copy and Run JAR on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
            aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }}/ViveroGardeniaBackend-0.0.1-SNAPSHOT.jar /home/${{ secrets.AWS_EC2_USER }}
            sudo fuser -k 8080/tcp
            java -jar ViveroGardeniaBackend-0.0.1-SNAPSHOT.jar
          EOF
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'